spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: Admin
  password: mysecretpassword
  driver-class-name: org.postgresql.Driver
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect



server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true